/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnessapp;

import java.util.Arrays;

/**
 *
 * @author Amr Ashraf
 */
public class ThirdScreen extends javax.swing.JFrame {
    String max1;
    String max2;
    String max3;
    String max4;
    
    String test1;
    String test2;
    String test3;
    

    /**
     * Creates new form ThirdScreen
     */
    public ThirdScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        FirstL1 = new javax.swing.JLabel();
        SecondL1 = new javax.swing.JLabel();
        SecondL2 = new javax.swing.JLabel();
        FirstL2 = new javax.swing.JLabel();
        ThirdL1 = new javax.swing.JLabel();
        ThirdL2 = new javax.swing.JLabel();
        FourthL1 = new javax.swing.JLabel();
        FourthL2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        FirstL = new javax.swing.JLabel();
        SecondL = new javax.swing.JLabel();
        ThirdL = new javax.swing.JLabel();
        FourthL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("FIRST");

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("SECOND");

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("THIRD");

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("FOURTH");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("calories burnt:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("calories burnt:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("calories burnt:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("calories burnt:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("heart rate increase:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("heart rate increase:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("heart rate increase:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("heart rate increase:");

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessapp/add.png"))); // NOI18N
        jButton5.setText("SHOW");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        FirstL1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FirstL1.setForeground(new java.awt.Color(204, 0, 0));

        SecondL1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SecondL1.setForeground(new java.awt.Color(204, 0, 0));

        SecondL2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        SecondL2.setForeground(new java.awt.Color(204, 0, 0));

        FirstL2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        FirstL2.setForeground(new java.awt.Color(204, 0, 0));

        ThirdL1.setForeground(new java.awt.Color(204, 0, 0));

        ThirdL2.setForeground(new java.awt.Color(204, 0, 0));

        FourthL1.setForeground(new java.awt.Color(204, 0, 0));

        FourthL2.setForeground(new java.awt.Color(204, 0, 0));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fitnessapp/exit.png"))); // NOI18N
        jButton6.setText("EXIT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        FirstL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FirstL.setForeground(new java.awt.Color(204, 0, 0));

        SecondL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SecondL.setForeground(new java.awt.Color(204, 0, 0));

        ThirdL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ThirdL.setForeground(new java.awt.Color(204, 0, 0));

        FourthL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        FourthL.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(FirstL, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(233, 233, 233)
                                .addComponent(SecondL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(138, 138, 138))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(120, 120, 120)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(FirstL1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FirstL2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThirdL1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(113, 113, 113)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ThirdL2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ThirdL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FourthL2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SecondL2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(SecondL1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FourthL1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(103, 103, 103)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FourthL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))))
                                .addContainerGap(38, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FirstL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SecondL, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstL1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondL1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstL2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondL2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ThirdL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ThirdL1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FourthL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FourthL1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FourthL2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ThirdL2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        FindMax();
        if(max1=="SWIMMING")
        {
            FirstL.setText("SWIMMING");
        FirstL1.setText(Double.toString(Main.CaloriesS));
        FirstL2.setText(Double.toString(Main.HRs));
        }
        else if(max1=="RUNNING")
        {
            FirstL.setText("RUNNING");
        FirstL1.setText(Double.toString(Main.Caloriesr));
        FirstL2.setText(Double.toString(Main.HRr));
        }
        else if (max1=="STRENGTH_TRAINING")
        {
            FirstL.setText("STRENGTH_TRAINING");
        FirstL1.setText(Double.toString(Main.Caloriesstre));
        FirstL2.setText(Double.toString(Main.HRstre));
        }
        else if(max1=="KICK_BOXING")
        {
            FirstL.setText("KICK_BOXING");
        FirstL1.setText(Double.toString(Main.Caloriesb));
        FirstL2.setText(Double.toString(Main.HRb));
        }
        ///////////////////////////////////////////////////////////
        
        
           if(max2=="SWIMMING")
        {
            SecondL.setText("SWIMMING");
        SecondL1.setText(Double.toString(Main.CaloriesS));
        SecondL2.setText(Double.toString(Main.HRs));
        }
        else if(max2=="RUNNING")
        {
            SecondL.setText("RUNNING");
        SecondL1.setText(Double.toString(Main.Caloriesr));
        SecondL2.setText(Double.toString(Main.HRr));
        }
        else if (max2=="STRENGTH_TRAINING")
        {
            SecondL.setText("STRENGTH_TRAINING");
        SecondL1.setText(Double.toString(Main.Caloriesstre));
        SecondL2.setText(Double.toString(Main.HRstre));
        }
        else if(max2=="KICK_BOXING")
        {
            SecondL.setText("KICK_BOXING");
        SecondL1.setText(Double.toString(Main.Caloriesb));
        SecondL2.setText(Double.toString(Main.HRb));
        }
           /////////////////////////////////////////////////////////////
           
              if(max3=="SWIMMING")
        {
            ThirdL.setText("SWIMMING");
        ThirdL1.setText(Double.toString(Main.CaloriesS));
        ThirdL2.setText(Double.toString(Main.HRs));
        }
        else if(max3=="RUNNING")
        {
            ThirdL.setText("RUNNING");
        ThirdL1.setText(Double.toString(Main.Caloriesr));
        ThirdL2.setText(Double.toString(Main.HRr));
        }
        else if (max3=="STRENGTH_TRAINING")
        {
            ThirdL.setText("STRENGTH_TRAINING");
        ThirdL1.setText(Double.toString(Main.Caloriesstre));
        ThirdL2.setText(Double.toString(Main.HRstre));
        }
        else if(max3=="KICK_BOXING")
        {
            ThirdL.setText("KICK_BOXING");
        ThirdL1.setText(Double.toString(Main.Caloriesb));
        ThirdL2.setText(Double.toString(Main.HRb));
        }
           ///////////////////////////////////////////////////////////////// 
           
           
           if(max4=="SWIMMING")
        {
            FourthL.setText("SWIMMING");
       FourthL1.setText(Double.toString(Main.CaloriesS));
        FourthL2.setText(Double.toString(Main.HRs));
        }
        else if(max4=="RUNNING")
        {
           FourthL.setText("RUNNING");
       FourthL1.setText(Double.toString(Main.Caloriesr));
        FourthL2.setText(Double.toString(Main.HRr));
        }
        else if (max4=="STRENGTH_TRAINING")
        {
            FourthL.setText("STRENGTH_TRAINING");
        FourthL1.setText(Double.toString(Main.Caloriesstre));
       FourthL2.setText(Double.toString(Main.HRstre));
        }
        else if(max4=="KICK_BOXING")
        {
            FourthL.setText("KICK_BOXING");
        FourthL1.setText(Double.toString(Main.Caloriesb));
        FourthL2.setText(Double.toString(Main.HRb));
        }
              

        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThirdScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThirdScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThirdScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThirdScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThirdScreen().setVisible(true);
            }
        });
    }
    public void FindMax()
    {
        int flag=0;
        int x[]={Main.CaloriesS,Main.Caloriesr,Main.Caloriesb,Main.Caloriesstre};
        Arrays.sort(x);
        //////////////////////////////////////////////////////////////////////////////
        if(x[3]!=x[2] && x[2]!=x[1] && x[1]!=x[0])
        {
            if(Main.CaloriesS==x[3])
                max1="SWIMMING";
            else if(Main.Caloriesr==x[3])
                max1="RUNNING";
            else if(Main.Caloriesb==x[3])
                max1="KICK_BOXING";
            else if(Main.Caloriesstre==x[3])
                max1="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[2])
                max2="SWIMMING";                             /////////////////case 1
            else if(Main.Caloriesr==x[2])
                max2="RUNNING";
            else if(Main.Caloriesb==x[2])
                max2="KICK_BOXING";
            else if(Main.Caloriesstre==x[2])
                max2="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[1])
                max3="SWIMMING";
            else if(Main.Caloriesr==x[1])
                max3="RUNNING";
            else if(Main.Caloriesb==x[1])
                max3="KICK_BOXING";
            else if(Main.Caloriesstre==x[1])
                max3="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[0])
                max4="SWIMMING";
            else if(Main.Caloriesr==x[0])
                max4="RUNNING";
            else if(Main.Caloriesb==x[0])
                max4="KICK_BOXING";
            else if(Main.Caloriesstre==x[0])
                max4="STRENGTH_TRAINING";
        }
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////
        else if(x[3]==x[2] && x[2]==x[1] && x[1]==x[0])
        {
             double y[]={Main.HRs,Main.HRr,Main.HRb,Main.HRstre};
                Arrays.sort(y);
                if(Main.HRs==y[3])
                    max1="SWIMMING";
                else if(Main.HRr==y[3])
                max1="RUNNING";
            else if(Main.HRb==y[3])
                max1="KICK_BOXING";
            else if(Main.HRstre==y[3])
                max1="STRENGTH_TRAINING";
                                                            ///////////case 2
            
                if(Main.HRs==y[2])
                    max2="SWIMMING";
                else if(Main.HRr==y[2])
                max2="RUNNING";
            else if(Main.HRb==y[2])
                max2="KICK_BOXING";
            else if(Main.HRstre==y[2])
                max2="STRENGTH_TRAINING";
                
                if(Main.HRs==y[1])
                    max3="SWIMMING";
                else if(Main.HRr==y[1])
                max3="RUNNING";
            else if(Main.HRb==y[1])
                max3="KICK_BOXING";
            else if(Main.HRstre==y[1])
                max3="STRENGTH_TRAINING";
                
                if(Main.HRs==y[0])
                    max4="SWIMMING";
                else if(Main.HRr==y[0])
                max4="RUNNING";
            else if(Main.HRb==y[0])
                max4="KICK_BOXING";
            else if(Main.HRstre==y[0])
                max4="STRENGTH_TRAINING";
        }
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        else if(x[3]==x[2] && x[2]==x[1])
        {
            String str1=null,str2=null,str3=null;
                   if(Main.CaloriesS==x[3])
                str1="SWIMMING";
            else if(Main.Caloriesr==x[3])
                str1="RUNNING";
            else if(Main.Caloriesb==x[3])
                str1="KICK_BOXING";/////////////////////////////////////////////////////case 3
            else if(Main.Caloriesstre==x[3])
                str1="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[2] && str1!="SWIMMING")
                str2="SWIMMING";
            else if(Main.Caloriesr==x[2]  && str1!="RUNNING")
                str2="RUNNING";
            else if(Main.Caloriesb==x[2]  && str1!="KICK_BOXING")
                str2="KICK_BOXING";
            else if(Main.Caloriesstre==x[2]  && str1!="STRENGTH_TRAINING")
                str2="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[1] && str1!="SWIMMING" && str2!="SWIMMING")
                str3="SWIMMING";
            else if(Main.Caloriesr==x[1] && str1!="RUNNING" && str2!="RUNNING")
                str3="RUNNING";
            else if(Main.Caloriesb==x[1]  && str1!="KICK_BOXING"  && str2!="KICK_BOXING")
                str3="KICK_BOXING";
            else if(Main.Caloriesstre==x[1]  && str1!="STRENGTH_TRAINING"  && str2!="STRENGTH_TRAINING")
                str3="STRENGTH_TRAINING";
            
             test3S(str1,str2,str3);
             max1=test1;
             max2=test2;
             max3=test3;
             if(Main.CaloriesS==x[0])
                max4="SWIMMING";
            else if(Main.Caloriesr==x[0])
                max4="RUNNING";
            else if(Main.Caloriesb==x[0])
                max4="KICK_BOXING";
            else if(Main.Caloriesstre==x[0])
                max4="STRENGTH_TRAINING";
        }
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        else if(x[2]==x[1] && x[1]==x[0])
        {
              String str2=null,str3=null,str4=null;
                   if(Main.CaloriesS==x[2])
                str2="SWIMMING";
            else if(Main.Caloriesr==x[3])
                str2="RUNNING";
            else if(Main.Caloriesb==x[3])
                str2="KICK_BOXING";
            else if(Main.Caloriesstre==x[3])
                str2="STRENGTH_TRAINING";
                                                                   ///////////////////////////case 4
            if(Main.CaloriesS==x[1] && str2!="SWIMMING")
                str3="SWIMMING";
            else if(Main.Caloriesr==x[1]  && str2!="RUNNING")
                str3="RUNNING";
            else if(Main.Caloriesb==x[1]  && str2!="KICK_BOXING")
                str3="KICK_BOXING";
            else if(Main.Caloriesstre==x[1]  && str2!="STRENGTH_TRAINING")
                str3="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[1] && str3!="SWIMMING" && str2!="SWIMMING")
                str4="SWIMMING";
            else if(Main.Caloriesr==x[1] && str3!="RUNNING" && str2!="RUNNING")
                str4="RUNNING";
            else if(Main.Caloriesb==x[1]  && str3!="KICK_BOXING"  && str2!="KICK_BOXING")
                str4="KICK_BOXING";
            else if(Main.Caloriesstre==x[1]  && str3!="STRENGTH_TRAINING"  && str2!="STRENGTH_TRAINING")
                str4="STRENGTH_TRAINING";
            
            test3S(str2,str3,str4);
            max2=test1;
            max3=test2;
            max4=test3;
            if(Main.CaloriesS==x[3])
                max1="SWIMMING";
            else if(Main.Caloriesr==x[3])
                max1="RUNNING";
            else if(Main.Caloriesb==x[3])
                max1="KICK_BOXING";
            else if(Main.Caloriesstre==x[3])
                max1="STRENGTH_TRAINING";
        }
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        else if(x[3]==x[2] && x[1] == x[0])
        {
             String str1=null,str2=null;
                   if(Main.CaloriesS==x[3])
                str1="SWIMMING";
            else if(Main.Caloriesr==x[3])
                str1="RUNNING";
            else if(Main.Caloriesb==x[3])
                str1="KICK_BOXING";
            else if(Main.Caloriesstre==x[3])
                str1="STRENGTH_TRAINING";
                                                           ///////////////////////////case 5
            if(Main.CaloriesS==x[2] && str1!="SWIMMING")
                str2="SWIMMING";
            else if(Main.Caloriesr==x[2]  && str1!="RUNNING")
                str2="RUNNING";
            else if(Main.Caloriesb==x[2]  && str1!="KICK_BOXING")
                str2="KICK_BOXING";
            else if(Main.Caloriesstre==x[2]  && str1!="STRENGTH_TRAINING")
                str2="STRENGTH_TRAINING";
            
            test2S(str1,str2);
            max1=test1;
            max2=test2;
            
            
            
                  if(Main.CaloriesS==x[1])
                str1="SWIMMING";
            else if(Main.Caloriesr==x[1])
                str1="RUNNING";
            else if(Main.Caloriesb==x[1])
                str1="KICK_BOXING";
            else if(Main.Caloriesstre==x[1])
                str1="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[0] && str1!="SWIMMING")
                str2="SWIMMING";
            else if(Main.Caloriesr==x[0]  && str1!="RUNNING")
                str2="RUNNING";
            else if(Main.Caloriesb==x[0]  && str1!="KICK_BOXING")
                str2="KICK_BOXING";
            else if(Main.Caloriesstre==x[0]  && str1!="STRENGTH_TRAINING")
                str2="STRENGTH_TRAINING";
            
            test2S(str1,str2);
            max3=test1;
            max4=test2;
        }
        /////////////////////////////////////////////////////////////////////////////////////////////////////
        else if (x[3]==x[2] && x[1]!=x[0])
        {
            String str1=null,str2=null;
                   if(Main.CaloriesS==x[3])
                str1="SWIMMING";
            else if(Main.Caloriesr==x[3])
                str1="RUNNING";
            else if(Main.Caloriesb==x[3])
                str1="KICK_BOXING";
            else if(Main.Caloriesstre==x[3])
                str1="STRENGTH_TRAINING";
                                                    ////////////////////////////////// case 6
            if(Main.CaloriesS==x[2] && str1!="SWIMMING")
                str2="SWIMMING";
            else if(Main.Caloriesr==x[2]  && str1!="RUNNING")
                str2="RUNNING";
            else if(Main.Caloriesb==x[2]  && str1!="KICK_BOXING")
                str2="KICK_BOXING";
            else if(Main.Caloriesstre==x[2]  && str1!="STRENGTH_TRAINING")
                str2="STRENGTH_TRAINING";
            
            test2S(str1,str2);
            max1=test1;
            max2=test2;
            
            
            if(Main.CaloriesS==x[1])
                max3="SWIMMING";
            else if(Main.Caloriesr==x[1])
                max3="RUNNING";
            else if(Main.Caloriesb==x[1])
                max3="KICK_BOXING";
            else if(Main.Caloriesstre==x[1])
                max3="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[0])
                max4="SWIMMING";
            else if(Main.Caloriesr==x[0])
                max4="RUNNING";
            else if(Main.Caloriesb==x[0])
                max4="KICK_BOXING";
            else if(Main.Caloriesstre==x[0])
                max4="STRENGTH_TRAINING";
            
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////    
            
        }
        else if (x[3]!=x[2] && x[1]==x[0])
        {
            if(Main.CaloriesS==x[3])
                max1="SWIMMING";
            else if(Main.Caloriesr==x[3])
                max1="RUNNING";
            else if(Main.Caloriesb==x[3])
                max1="KICK_BOXING";
            else if(Main.Caloriesstre==x[3])
                max1="STRENGTH_TRAINING";
                                                        /////////////////////////////////////case 7
            if(Main.CaloriesS==x[2])
                max2="SWIMMING";
            else if(Main.Caloriesr==x[2])
                max2="RUNNING";
            else if(Main.Caloriesb==x[2])
                max2="KICK_BOXING";
            else if(Main.Caloriesstre==x[2])
                max2="STRENGTH_TRAINING";
            
            
            
            String str1=null ,str2=null;
            
                   if(Main.CaloriesS==x[1])
                str1="SWIMMING";
            else if(Main.Caloriesr==x[1])
                str1="RUNNING";
            else if(Main.Caloriesb==x[1])
                str1="KICK_BOXING";
            else if(Main.Caloriesstre==x[1])
                str1="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[0] && str1!="SWIMMING")
                str2="SWIMMING";
            else if(Main.Caloriesr==x[0]  && str1!="RUNNING")
                str2="RUNNING";
            else if(Main.Caloriesb==x[0]  && str1!="KICK_BOXING")
                str2="KICK_BOXING";
            else if(Main.Caloriesstre==x[0]  && str1!="STRENGTH_TRAINING")
                str2="STRENGTH_TRAINING";
            
            test2S(str1,str2);
            max3=test1;
            max4=test2;
            
            
            
        }
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////
        else if(x[2]==x[1] && x[3]!=x[2] && x[1]!=x[0])
        {
            if(Main.CaloriesS==x[3])
                max1="SWIMMING";
            else if(Main.Caloriesr==x[3])
                max1="RUNNING";
            else if(Main.Caloriesb==x[3])
                max1="KICK_BOXING";
            else if(Main.Caloriesstre==x[3])
                max1="STRENGTH_TRAINING";
                                                             ///////////case 8
            if(Main.CaloriesS==x[0])
                max4="SWIMMING";
            else if(Main.Caloriesr==x[0])
                max4="RUNNING";
            else if(Main.Caloriesb==x[0])
                max4="KICK_BOXING";
            else if(Main.Caloriesstre==x[0])
                max4="STRENGTH_TRAINING";
            
            
             String str1=null ,str2=null;
            
                   if(Main.CaloriesS==x[2])
                str1="SWIMMING";
            else if(Main.Caloriesr==x[2])
                str1="RUNNING";
            else if(Main.Caloriesb==x[2])
                str1="KICK_BOXING";
            else if(Main.Caloriesstre==x[2])
                str1="STRENGTH_TRAINING";
            
            if(Main.CaloriesS==x[1] && str1!="SWIMMING")
                str2="SWIMMING";
            else if(Main.Caloriesr==x[1]  && str1!="RUNNING")
                str2="RUNNING";
            else if(Main.Caloriesb==x[1]  && str1!="KICK_BOXING")
                str2="KICK_BOXING";
            else if(Main.Caloriesstre==x[1]  && str1!="STRENGTH_TRAINING")
                str2="STRENGTH_TRAINING";
            
            test2S(str1,str2);
            max2=test1;
            max3=test2;    
        }

        
        //////////////////////////////////////////////////////////////////////////////////////////////////////
    }
    public  void test2S(String s1, String s2)
    {
        double x=0,y=0;
        if (s1=="SWIMMING")
            x=Main.HRs;
        else if (s1=="RUNNING")
            x=Main.HRr;                         //////find s1
           else if (s1=="KICK_BOXING")
            x=Main.HRb; 
        else if (s1=="STRENGTH_TRAINING")
            x=Main.HRstre;
     /////////////////////////////////////////////   
        if (s2=="SWIMMING")
            y=Main.HRs;
        else if (s2=="RUNNING")
            y=Main.HRr;
           else if (s2=="KICK_BOXING")//////////////////////////////find s2
            y=Main.HRb; 
        else if (s2=="STRENGTH_TRAINING")
            y=Main.HRstre;
      ///////////////////////////////////////////////  
        double a[]={x,y};                                    ///////////sort x,y
        Arrays.sort(a);
       //////////////////////////////////////////// 
        
        if(a[1]==Main.HRs)
            test1="SWIMMING";
        else if(a[1]==Main.HRr)
            test1="RUNNING";                         ////////put test 1
         else if(a[1]==Main.HRb)
            test1="KICK_BOXING";
        else if(a[1]==Main.HRstre)
            test1="STRENGTH_TRAINING";
        ///////////////////////////////////////////////////
        if(a[0]==Main.HRs)
            test2="SWIMMING";
        else if(a[0]==Main.HRr)
            test2="RUNNING";
         else if(a[0]==Main.HRb)
            test2="KICK_BOXING";                   /////put test2
        else if(a[0]==Main.HRstre)
            test2="STRENGTH_TRAINING";
    }
    
    public  void test3S(String s1, String s2 , String s3)
    {
        double x=0,y=0,z=0;
        
       if ( s1=="SWIMMING")
            x=Main.HRs;
        else if (s1=="RUNNING")
            x=Main.HRr;                         //////find s1
           else if (s1=="KICK_BOXING")
            x=Main.HRb; 
        else if (s1=="STRENGTH_TRAINING")
            x=Main.HRstre;
     /////////////////////////////////////////////   
        if (s2=="SWIMMING")
            y=Main.HRs;
        else if (s2=="RUNNING")
            y=Main.HRr;
           else if (s2=="KICK_BOXING")//////////////////////////////find s2
            y=Main.HRb; 
        else if (s2=="STRENGTH_TRAINING")
            y=Main.HRstre;
      ///////////////////////////////////////////////
      
      if (s3=="SWIMMING")
            z=Main.HRs;
        else if (s3=="RUNNING")
            z=Main.HRr;
           else if (s3=="KICK_BOXING")//////////////////////////////find s2
            z=Main.HRb; 
        else if (s3=="STRENGTH_TRAINING")
            z=Main.HRstre;
      
      //////////////////////////////////////////////////////////////
      double a[]={x,y,z};                                    ///////////sort x,y,z
        Arrays.sort(a);
        ///////////////////////////////////////////////////
        
        
        if(a[2]==Main.HRs)
            test1="SWIMMING";
        else if(a[2]==Main.HRr)
            test1="RUNNING";                         ////////put test 1
         else if(a[2]==Main.HRb)
            test1="KICK_BOXING";
        else if(a[2]==Main.HRstre)
            test1="STRENGTH_TRAINING";
        /////////////////////////////////////////////////////////
        if(a[1]==Main.HRs)
            test2="SWIMMING";
        else if(a[1]==Main.HRr)
            test2="RUNNING";                         ////////put test 2
         else if(a[1]==Main.HRb)
            test2="KICK_BOXING";
        else if(a[1]==Main.HRstre)
            test2="STRENGTH_TRAINING";
        ///////////////////////////////////////////////////
        if(a[0]==Main.HRs)
            test3="SWIMMING";
        else if(a[0]==Main.HRr)
            test3="RUNNING";
         else if(a[0]==Main.HRb)
            test3="KICK_BOXING";                   /////put test3
        else if(a[0]==Main.HRstre)
            test3="STRENGTH_TRAINING";
        
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FirstL;
    private javax.swing.JLabel FirstL1;
    private javax.swing.JLabel FirstL2;
    private javax.swing.JLabel FourthL;
    private javax.swing.JLabel FourthL1;
    private javax.swing.JLabel FourthL2;
    private javax.swing.JLabel SecondL;
    private javax.swing.JLabel SecondL1;
    private javax.swing.JLabel SecondL2;
    private javax.swing.JLabel ThirdL;
    private javax.swing.JLabel ThirdL1;
    private javax.swing.JLabel ThirdL2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
